### ISSUE TITLE
PurePerms 1.1.12 causes PM 1.6 crash when player limit hit 

### ISSUE THREAD

**Issue by BlindTail** [PurePlugins/PurePerms#90] opened 2015-09-13 08:30 UTC
As soon as the server hits the player limit set in server.properties, it will crash with the following error:

```
Error: Call to a member function toString() on null
File: /PurePerms_v1.1.12.phar/src/_64FF00/PurePerms/PurePerms
Line: 661
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: PurePerms v1.1.12

Code:
[652]     }
[653] 
[654]     /**
[655]      * @param Player $player
[656]      */
[657]     public function unregisterPlayer(Player $player)
[658]     {
[659]         $this->getLogger()->debug($this->getMessage("logger_messages.unregisterPlayer", $player->getName()));
[660] 
[661]         $uniqueId = $player->getUniqueId()->toString();
[662] 
[663]         if(isset($this->attachments[$uniqueId])) $player->removeAttachment($this->attachments[$uniqueId]);
[664] 
[665]         unset($this->attachments[$uniqueId]);
[666]     }
[667] }
[668] 
[669] 
[670] 
[671] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #23 [Protocol 34; API 1.13.0]```

**Comment by BlindTail** [comment] 2015-09-13 09:19
On second thought; This may not be a bug in your code.

With zero plugins installed, PocketMine 1.6 is allowing 1 more player to join above the limit, and on the second player to join above the limit it says "server full". I think this is causing problems with various plugins. 

That's my theory at least; because if I run it with a modified version of SimpleAuth (with the toString fix), the SimpleAuth crashes with the same error as your Plugin does:

Call to a member function toString() on null

So now...I have no idea where to dig through the PocketMine source to find where the bug is that is allowing one more than max players to connect. And Shoghi doesn't want any bugs reported on "bleeding". So I'm not sure where to go from here. It's pretty much a show-stopper bug; as your server WILL crash when it reaches max players if you have either SimpleAuth or PurePerms installed.

**Comment by flaxues** [comment] 2015-09-13 18:59
I hope or Shoghicp or 64FF00 fix this soon

my server crashes every 20 seconds now :(

**Comment by BlindTail** [comment] 2015-09-13 21:49
Note that new jenkins build (PocketMine-MP_1.6dev-27_mcpe-0.12_885fc07e_API-1.13.0.phar) does NOT fix the problem. Although judging by his commit; it looks like he is working on that area.

**Comment by jazzwhistle** [comment] 2015-09-14 00:38
Nice work... but I'm not sure about the max player limit = crash theory. I'm running 1.6dev23 with latest SimpleAuth 1.7.1 from GitHub and PurePerms (PurePerms_v1.0.9 (v1.1.0-INDEV).phar), the server is full all the time (except for a minute or so after crashes...) and it's not crashing PurePerms or SimpleAuth when it goes to 40/41 players. Actually it even gets up to 45/40... so no idea what is going on! With this latest PurePerms I'm getting crashes with the exact error you show but sometimes when the server is only half full.

**Comment by flaxues** [comment] 2015-09-14 16:05
My disk is like full because of crashdumps now because of PurePerms crashing every 10 seconds :-1:

**Comment by Taytan9912** [comment] 2015-09-14 16:55
When someone kill players then server crashed, this is by PurePerms? Because crash log is from PurePerms

**Comment by BlindTail** [comment] 2015-09-14 17:33
Does this fix work?

https://github.com/PurePlugins/PurePerms/pull/91

**Comment by jazzwhistle** [comment] 2015-09-15 19:29
On further testing you may well be right. I'll test that fix now

**Comment by Taytan9912** [comment] 2015-09-15 19:55
In pocketmine 1.6dev-29 it's good :/

**Comment by jazzwhistle** [comment] 2015-09-15 23:04
Not for me... it can't possibly work as $player is not even declared in one function.

**Comment by jazzwhistle** [comment] 2015-09-15 23:05
I just added if (null !== ($player->getUniqueId())) before line 661 in PurePerms.php and now it works perfectly with 28 and 29.

**Comment by flaxues** [comment] 2015-09-16 15:03
I maded a pull request.

**Comment by BlindTail** [comment] 2015-09-18 21:55
> I just added if (null !== ($player->getUniqueId())) before line 661 in PurePerms.php and now it works 

Yes, this modified code seems to work:

```
		if (null !== ($player->getUniqueId()))
		{	
        	$uniqueId = $player->getUniqueId()->toString();
        	
        	if(isset($this->attachments[$uniqueId])) $player->removeAttachment($this->attachments[$uniqueId]);
		
        	unset($this->attachments[$uniqueId]);
        }
```

**Comment by Pub4Game** [comment] 2015-09-21 16:24
@64FF00 When you can fix it?

**Comment by Taytan9912** [comment] 2015-09-22 06:38
@Pub4Game try with other PocketMine version, i have pocketmine rc 343 and this is fine for me ;)

**Comment by markkrueg** [comment] 2015-09-24 04:07
@Taytan9912 I just tested the current release version of PurePerms (1.1.12) with PocketMine-MP-PR 343, and the bug is DEFINITELY STILL THERE. A reminder of the testing process to reproduce the bug:

Set your server.properties max-players=2. Connect the first player. Then a second. Then a third. When the third player tries to connect (using PR 343), I get the following error:

```
Error: Call to a member function toString() on null
File: /PurePerms_v1.1.12-PMv1.6dev.phar/src/_64FF00/PurePerms/PurePerms
Line: 661
```

**Comment by 64FF00** [comment] 2015-10-03 14:03
Fixed in the latest commit

**Closed by 64FF00** 2015-10-03 14:03 UTC
Labels: Bug!, Enhancement! :D

**Comment by BlindTail** [comment] 2015-10-05 05:50
Tested this issue using PurePerms v1.2.0  Unfortunately, it is still producing a similar error with every PocketMine 1.6 version I have tested. Which version did you test against?

I have tested:
PocketMine-MP_1.6dev-35_mcpe-0.12_a7e5e33d_API-1.13.0.phar
PocketMine-MP_1.6dev-43_0.12-items_84be56fe_API-1.13.0.phar
PocketMine-MP_1.6dev_PR-3475_24f8de2c_API-1.13.0.phar (MP-PR#343)

All produce the same error:

```
Error: Call to a member function toString() on null
File: /PurePerms_v1.2.0.phar/src/_64FF00/PurePerms/PurePerms
Line: 437

[437]             $uniqueId = $player->getUniqueId()->toString();
```

**Comment by PEMapModder** [comment] 2015-10-05 13:12
Which event are you using?

**Comment by BlindTail** [comment] 2015-10-05 20:23
> Which event are you using?

@PEMapModder I'm not sure if you were speaking to me or 64FF00. All I am doing is testing for bugs by doing this:

1) Install clean PocketMine-MP 1.6
2) Drop new PurePerms 1.2.0 into Plugins
3) set max-players=1
4) start server
5) When one player joins all is fine.
6) When second player joins server crashes because of "Call to a member function toString() on null"

I think this is the same issue we've been tracking here since the beginning.

Here is the full crashlog:
https://gist.github.com/BlindTail/18451447c30d44698cda
