### ISSUE TITLE
Denying permissions

### ISSUE THREAD

**Issue by AryToNeX** [PurePlugins/PurePerms#70] opened 2015-08-27 15:27 UTC
Hi! I setted in my groups.yml:
```
User:
  isDefault: true
  inheritance: []
  permissions:
  - -myplot.command.biome
  - -walkingparticles
  - -walkingparticles.command
  - myplot.command.claim
  worlds: []
VIP:
  isDefault: true
  inheritance:
  - User
  permissions:
  - myplot.command.biome
  - armorspawn.receive
  - walkingparticles
  - walkingparticles.command
  worlds: []
```

But VIPs don't have permission to do /p biome and /wparticles and armor is gived to all players! What I'm doing wrong? Is it a bug?

**Comment by 64FF00** [comment] 2015-08-28 15:27
@AryToNeX Could you please check if this has been fixed in the latest version?

**Comment by AryToNeX** [comment] 2015-08-28 22:21
@64FF00 No, it still persists :cry:

**Comment by 64FF00** [comment] 2015-08-29 01:53
@AryToNeX Hmm... What about the other perms?

**Comment by AryToNeX** [comment] 2015-08-29 08:43
@64FF00 the other perms work correctly; I have this problem only if I deny a permission to a X group and grant the permission in another Y group that inherit X group's permissions, so I have to split group's permissions..

**Comment by AryToNeX** [comment] 2015-08-29 08:44
@64FF00 the other perms work correctly; I have this problem only if I deny a permission to a X group and grant the permission in another Y group that inherit X group's permissions, so I have to split group's permissions..

**Comment by 64FF00** [comment] 2015-08-29 15:19
@AryToNeX I see... Can you post your groups.yml here?

**Comment by AryToNeX** [comment] 2015-08-31 14:30
@64FF00 I've modified my groups.yml in order to workaround this bug.. so sorry, but it was exactly like in first post

**Comment by 64FF00** [comment] 2015-08-31 14:34
@AryToNeX Does the default groups.yml work well then?

**Comment by AryToNeX** [comment] 2015-08-31 15:07
@64FF00 I haven't tried default groups.yml, but in latest version walkingparticles works well

**Comment by 64FF00** [comment] 2015-10-17 12:24
@AryToNeX I'm pretty sure this is caused by other plugins. I'll take a look at them and make pull requests if needed, so please hold on

**Closed by 64FF00** 2015-10-17 12:24 UTC
Labels: Bug!
