### ISSUE TITLE
[MAJOR] Case sensitive issue!

### ISSUE THREAD

**Issue by brunyman** [PurePlugins/PurePerms#50] opened 2015-07-30 05:40 UTC
Hi, there is a major issue with this plugin, if I brunyman have some permissions defined and a player joins the server with this name Brunyman it's seen as a different player by the server but not by this plugin and he has all my permissions.

**Comment by PEMapModder** [comment] 2015-07-30 09:00
Do you mean SimpleAuth, instead of the server, identifying you as the same player?

**Comment by PEMapModder** [comment] 2015-07-30 09:00
If so, it is a SimpleAuth issue.

**Comment by 64FF00** [comment] 2015-07-30 09:08
@PEMapModder Tysm <3

**Comment by brunyman** [comment] 2015-08-02 07:03
No, it's not simple auth, because simple auth sees them as a different player, witch it should, but your plugin sees them as the same player, so it does not count for case letters brunyman and Brunyman have the same permissions, so problem not fixed, did you even test this?

**Comment by PEMapModder** [comment] 2015-08-02 10:17
And the problem is in SimpleAuth. Players are supposed to be identified with case-insensitive names.

**Comment by 64FF00** [comment] 2015-08-04 12:07
@brunyman @PEMapModder Um so should I leave this here or... may I close this

**Comment by PEMapModder** [comment] 2015-08-04 20:27
Close it.
PocketMine players are case-insensitive by nature. Look at the filenames in the players/ diirectory for example.

**Comment by 64FF00** [comment] 2015-08-06 14:35
Tysm @PEMapModder

**Closed by 64FF00** 2015-08-06 14:35 UTC
Labels: Done!, Invalid!
