### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Taytan9912** [PurePlugins/PurePerms#92] opened 2015-09-14 15:03 UTC
PocketMine-MP Crash Dump Mon Sep 14 14:41:27 UTC 2015

Error: Call to a member function toString() on null
File: /PurePerms_v1.1.12-PMv1.6dev.phar/src/_64FF00/PurePerms/PurePerms
Line: 661
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: PurePerms v1.1.12

Code:
[652]     }
[653] 
[654]     /**
[655]      * @param Player $player
[656]      */
[657]     public function unregisterPlayer(Player $player)
[658]     {
[659]         $this->getLogger()->debug($this->getMessage("logger_messages.unregisterPlayer", $player->getName()));
[660] 
[661]         $uniqueId = $player->getUniqueId()->toString();
[662] 
[663]         if(isset($this->attachments[$uniqueId])) $player->removeAttachment($this->attachments[$uniqueId]);
[664] 
[665]         unset($this->attachments[$uniqueId]);
[666]     }
[667] }
[668] 
[669] 
[670] 
[671] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #21 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux node65 3.14.38-pukawka-v2-grsec #1 SMP Wed Apr 15 05:20:55 CEST 2015 x86_64
PHP Version: 5.6.9
Zend version: 2.6.0
OS : Linux, linux

**Comment by flaxues** [comment] 2015-09-14 15:52
Duplicate of #90

**Comment by 64FF00** [comment] 2015-09-14 16:31
@flaxues Thank you.

**Closed** 2015-09-14 16:32 UTC
Labels: Done!, Invalid!
